apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hvw342mcf-go 
  janus-idp.io/tekton: hvw342mcf-go
  backstage.io/kubernetes-id: hvw342mcf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hvw342mcf-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml